language: node_js
sudo: false
node_js:
- 12
env:
  global:
  - NODE_ENV=test
  - COMMIT=${TRAVIS_COMMIT::8}
  - secure: QO8O0uRDqrXPZtRNmWhn9b0WLPQO5w/EWVvVUAP0Hm/0yiw5f9kJM+VVq1WLByCwao4QNqA9Xl1LCYl2VeaS6Hfg9r8JZ/Wv636aje+5pUZnDcVgvNQKruxsgRoHGet+IyVytj2NoSyrYD3NcZwx5wSrt4xtep4ANAli1etqtOr+9L1rkPAVbFeTK8dYCoudSGPRO38RuT6xMjKLkjNpw0Z9SqNLda3ocyAezPGKOAda85FXbpGxQZs+lRtIS46pvZgu/86KYYDyf213NyX9K70WP/bmcVMD8GLCMfjblUM+iQcexzZPSZDyKxkIl01xvNIrHJ2DVOVhkDR3XHeWxdaWwqwkHOJ8QpjeYQJcXr1j7qG6R9GI8L8u7cgord2j6+6kKquHyg3bvHjvuGmmt6QGwPwvCasnNUOS82v59mjZKeeJxWYvIA/ZbiMaiIW+2gb/AxXNskgaxg2N5CNYNtvAC5acgOGMyrDlZKnjfmxgd+OVm9qRfv1O++NMpgL+Dqi5qXja4mZkChZnYVGekcv6E8tMmRy4/hJIL+karjs/pO3fVA2sp7lAgrFMVicfERWewHkkR0Ql/3woEi2DqQg3pMuugs17h7PGyebbhEqQ+PpUev20P7hjWLuAQKmhP2aYgIwWiEMAICUZ7Mnl+Qy2WKJ3jmImNzjVkZRtayk=
  - secure: F3+K9h6oUfoUev9Y7CmddbysajLnuxqC4ucL/u7E/UnrE89odRzah74HukEiMp5geHm0y0DLj84Wcfqx2coHxwLbcox2VPhGeA0WgLUePoGU4n05eg6QkilU5LkRCiIImsPfCpPwQNqarGQo8OIXIDwkkn0n4LAtZYMkiLRYvoTPsmkcoIuaven/gwf5FU4cZW5qkRTWaeSg4n3/gEGEU1OWepxeR1R7hwsS5U/F7gwVTt1DT20t0xCn6gg9iynOBHOXq6UM9LBAJaUMzYFZItfvJOqtzgrlqBwWHeBPYZDMRgv5Ir4gG5E8wdYV9cIemkXt/9Bnp+VFpZlG6PONE9T66AWJvS/ZYPRWE/txm24uoC2szuaDafVsAwZ1n28y1mwxNfRbxxbWhd9MDnZ5CkieioIetAgfcuSk0mN9aGb8/dUTwRoajSnWdhzSlPL5LtZrx1AoJ9Sp6Fi5JmqFbIKvlycecMPtn2lM9lNGX9nWwvifrl2k7jf9XGvzYm+SoScAC0MRR+dvZkvI+mywPFG6T46aNg43X+eqkFXLc/n8hov2r4GREghriPxbx7BMYqzuHnt9lpSL4fgppyTjFJGEsKBK/+k+7i1MYgZwK18j80K6W2UMtQStshqo8QXnrCOfej7+KD54HEo8ItR4c4KwomgzuT5gIb0roK+C5rQ=
  - secure: rVt1LEQ3LhNwvNd4r7l5qvq+8lTpGM475EuR2xQ8TRFePRszgeXs/eMAPbEWnkbtP4rjYuYEPwElUcK/35xhP/0xD3KCTE8KeUN0flOPyKWyvR9ms5acPwM5PXHz5I1RuzC1ZaZoXSXk2ylZxMbUpeS2NhGqko5iZrU07lp24v4mXksdoq214ZhaeiHZ2/jdcu12y/jqPUQd/NBexfhZUkwSxrUIuj/xNKKQwU4R3rDPcjt1dAo/eOWs3vnVhq9c0b80V5uNXgbrDmgv0GotqctE1kbGy16VCkBdlu8hHAnoOfuz4OwvbW1zYYocnChLAYsKSk8x0jFA/o0djKUg1E5SPVY8ZFG9FTgPXlXc1gI0kqQyIlFVv1eegbGY8/IBGFhQlApOkgfg2uKTCw7zqiYABGz9lvgTjMGLwoyzCYf1X6I75Ot8yiMbVRY17Yen0lz9ihWMDplGdCzTeNlkykvOL0bWG04r0SUC/Sa2YWcYYk3HRYKkLGQK0K3bgYkleZddRSd0wbC8fxYpJ+P2LyVuYjNT9fP1ClpoP0M1dtwowoVKnxpNr0iYG5PHuavcsex3HdXpH6yLrhHm0Z6MCi677aiXhpoA9I9gdA0OcfLigCGq1913fclc30APBoGUPySWw+bPPdhBM6l9gOZASR8BNhWSm4ZUMH5WTWs4C/M=
script:
- docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
- export REPO=podshows/podradioff
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH
  ; fi`
- docker build -f Dockerfile -t $REPO:$COMMIT .
- docker tag $REPO:$COMMIT $REPO:$TAG
- docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
- docker push $REPO
before_deploy:
- eval "$(ssh-agent -s)"
- openssl aes-256-cbc -K $encrypted_7f0a4dc54bb1_key -iv $encrypted_7f0a4dc54bb1_iv
  -in .deploy_key.enc -out /tmp/deploy_key -d
- chmod 600 /tmp/deploy_key
- ssh-add /tmp/deploy_key
- ssh-keyscan "$SERVER" >> ~/.ssh/known_hosts
deploy:
- provider: script
  script: "./deploy.sh"
  on:
    branch: master
before_install:
